---
- include_vars: "vars/{{ ansible_os_family }}.yml"

- name: override vars
  include: nfs_users.yaml

- name: Ensures the required nfs share groups exist on the server
  group:
    name: "{{ item.name }}"
    gid: "{{ item.gid }}"
    system: "{{ item.system|default(false) }}"
  with_items:
    - "{{ nfs_groups }}"

- name: Add users to secondary groups
  user:
    name: "{{ item.user }}"
    group: "{{ item.user }}"
    groups: "{{ item.secondary_group }}"
    append: true
  with_items:
    "{{ nfs_secondary_groups }}"
